global:
    technology: magento
    technology_version: 2
    process_timeout: 120
    log_dir: build/logs
    package_dir: build/dist
    clean: true

# Tools run by the "analyze" command
tools:
    # Runs PHPUnit tests
    # phpunit:
    #   configuration: dev/tests/unit
    #   coverage: true

    # Will recursively run 'php -l' on matching files
    phplint:
        files:
            - app/code

    # Runs PHP_CodeSniffer
    phpcs:
        files:
            - app/code
            - app/design
        standard: vendor/smile/php-codesniffer-rules-magento-2/SmileMagento2
        extensions:
            - php
            - phtml

    # Runs PHPMD
    phpmd:
        files:
            - app/code
        rulesets:
            - cleancode
            - codesize
            - design
            - vendor/smile/php-md-rules/resources/rulesets/Magento2/naming.xml
            - unusedcode

    # Runs PDepend
    pdepend:
        files:
            - app/code
        enable:
            - jdepend-xml
            - jdepend-chart
            - summary-xml
            - overview-pyramid

    # Runs phpcpd
    phpcpd:
        files:
            - app/code

    # Runs SmileAnalyser
    smileanalyser:
        config_file: .smileanalyser.yaml

    # Runs Qafoo Quality Analyzer
    visualization:
        files:
            - app/code
            - app/design
        hostname: localhost
        port: 8080

# Package creation
package:
    # Package format (available: tar, tar,gz, tar.bz2, zip, phar, none)
    format: tar.gz
    # Commands to run during packaging
    commands:
        - composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction
    # Paths to exclude from package
    excludes:
        - ./architecture
        - ./build
        - ./docs
        - ./scripts
        - ./lxcfile
        - ./CHANGELOG.md
        - ./CONTRIBUTING.md
        - ./COPYING.txt
        - ./ISSUE_TEMPLATE.md
        - ./README.md
        - ./.gitignore
        - ./.php_cs
        - ./.spbuilder.yaml
        - ./.smileanalyser.yaml
        - ./.travis.yml
        - ./.htaccess.sample
        - ./nginx.conf.sample
        - ./package.json.sample
        - ./package.json
        - ./auth.json
        - ./php.ini.sample
        - ./Gruntfile.js.sample
        - ./Gruntfile.js
        - .htaccess
    skipRoot: true
    vcs:
        # VCS Type (available: git, svn)
        type: git
        # Repository URL (defaults to local git repo, with .git extension, not the https one)
        url: ~

# Push to external tools
push:
    # Push to a file in the global.log_dir folder
    file:
        location: resume.xml

    # Push to Jenkins Viewer
    jenkins_viewer:
        location: http://pic-php-viewer.vitry.intranet/push
