<?php
use SportStore\CurrencyConverter\Block\ConverterBlock;
use Magento\Framework\Escaper;
/* @var ConverterBlock $block */
/* @var Escaper $escaper */
?>
<section class="converter">
    <h2>Currency Converter</h2>
    <form action="#">
        <label for="original-currency"><?= $escaper->escapeHtml(__('Original currency: ')); ?></label>
        <select name="original-currency" id="original-currency">
            <option value="dollar"><?= $escaper->escapeHtml(__('Dollar')); ?></option>
            <option value="euro"><?= $escaper->escapeHtml(__('Euro')); ?></option>
            <option value="pound"><?= $escaper->escapeHtml(__('Pound')); ?></option>
        </select>

        <label for="amount"><?= $escaper->escapeHtml(__(' Amount: ')); ?></label>
        <input type="number" name="amount" id="amount">

        <label for="target-currency"><?= $escaper->escapeHtml(__('Target currency: ')); ?></label>
        <select name="target-currency" id="target-currency">
            <option value="dollar"><?= $escaper->escapeHtml(__('Dollar')); ?></option>
            <option value="euro"><?= $escaper->escapeHtml(__('Euro')); ?></option>
            <option value="pound"><?= $escaper->escapeHtml(__('Pound')); ?></option>
        </select>

        <input type="submit" value="Calculate">
    </form>
</section>
